---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - metallb.yaml
  - ingress-nginx.yaml
  - cert-manager.yaml
  - cnpg-system.yaml
  - metrics-server.yaml
  - local-path-provisioner.yaml
