---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: grafana
  namespace: monitoring
  annotations:
    gethomepage.dev/group: Selfhosted
    gethomepage.dev/enabled: "true"
    gethomepage.dev/pod-selector: ""
    gethomepage.dev/icon: grafana.png
    gethomepage.dev/name: Grafana
spec:
  parentRefs:
    - name: eg
      namespace: envoy-gateway-system
      sectionName: https
  hostnames:
    - grafana.local
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: monitoring-kps-grafana
          port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: prometheus
  namespace: monitoring
  annotations:
    gethomepage.dev/group: Selfhosted
    gethomepage.dev/enabled: "true"
    gethomepage.dev/pod-selector: ""
    gethomepage.dev/icon: prometheus.png
    gethomepage.dev/name: Prometheus
spec:
  parentRefs:
    - name: eg
      namespace: envoy-gateway-system
      sectionName: https
  hostnames:
    - prometheus.local
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: monitoring-kps-kube-promet-prometheus
          port: 9090
