---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-secrets
  namespace: monitoring
stringData:
  admin-user: ENC[AES256_GCM,data:X8to6q8=,iv:qJ1KYzBmfIgKY8cLTUcTMiXhClRmr/EAg7X1MUCcXHA=,tag:eZwNkN+htrWjaacPYaN7wQ==,type:str]
  admin-password: ENC[AES256_GCM,data:vMyrQ20IBTqFzg==,iv:p6uatSjcj/FYb0PhsvPJR54DLy29UIlWC3ZNRG7kFC4=,tag:nCpSUmDIqPv9tNWg32eckg==,type:str]
sops:
  age:
    - recipient: age1vtnndcu4fmcthtam7zqlpt2nuqms7vhfdmljs08zzxkrnjy7344qt0td4v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhRmxNZVMyOWc5M0ZMZ2ow
        d1ZaMDVwNDRYbWJTa0lyQzkvZGg4SzQxbWlrClJuN3ZUcHlPZlNnNitTa1RuUVBi
        TWZkbVFCYnVoTGxnRUFxK3B3VkFyMzgKLS0tIDVkUlliUFVaYWp5VnpFZ3dzcDRx
        ZFROV0NKdHhheFcvWThOK1NCaWpCTjQKbdd+VVpamLDyPUqNv+CQ2aEU+4wq9XRY
        zVL8HuK3HntizznR30LYhoGC9dNjifsv1+59Cdbo9wD5kiYc14wWvA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-30T07:41:03Z"
  mac: ENC[AES256_GCM,data:VoEzafdKlZ0KV3cDo5g5PteSUyMijkm9D1c6FP0ZuZ0DFKx63P1KoFo9H1Tb/pX9wTSjpNoDqJrJIuUgcsg6XylMshgoQY+8n3Vv8j6JhHhWWFkWnX51LPk6b1vp1/XK2PR4NYjPxqMmvIzZ+Lmw+jOV4RCm+oC97yi+DzZRnXw=,iv:6q4DTC9PAQ/Vg4KY+ixlO6eiPhuL844/cHvrHH1bTQ4=,tag:O+zcwjX3zqiAKBiptrArJA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
