---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: wallabag
  namespace: wallabag
  annotations:
    gethomepage.dev/group: Selfhosted
    gethomepage.dev/enabled: "true"
    gethomepage.dev/pod-selector: ""
    gethomepage.dev/icon: wallabag.png
    gethomepage.dev/name: Wallabag
spec:
  parentRefs:
    - name: eg
      namespace: envoy-gateway-system
      sectionName: https
  hostnames:
    - wallabag.local
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: wallabag
          port: 80
