apiVersion: v1
kind: Secret
metadata:
  name: wallabag-db-creds
  namespace: wallabag
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:10NaYgbmc6k=,iv:7ZFsMgE0zBGh+Eu8Heh5IsaEttD2vn/mEj2c6AKNi2I=,tag:02EjGFu9OFaGIm/2KMbYVg==,type:str]
  password: ENC[AES256_GCM,data:7Wu8PqFw855NlA==,iv:MyQb6WnDFtJy7AfLO5GpK6iLq3FOJDWpUO1lGGg98r4=,tag:TvAHH6JExZ928iCvHHZjGQ==,type:str]
sops:
  age:
    - recipient: age1vtnndcu4fmcthtam7zqlpt2nuqms7vhfdmljs08zzxkrnjy7344qt0td4v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlRXNvMFkxZHJoUUpJeXY1
        ZlpLZDNHalg5bVU0d2F0REUzNnl0ZXJGK0ZNClRXdE5zUXNua0Y5NUhibmZmL2hz
        SWNLTUUxUE1YS093MU9mbmJHWmhYS1EKLS0tIGNvekFpbXpEOU5yZTZCOExYK2Yz
        QkJDM215ZWk5Q2wra3IraEJpRzMzSjgKC8LoInzJMzhVSR21MqjBo/Llt2kK+XxT
        WtYq8RBvMj1UqjGe+zm7MK+wHx+OkhmBttXbf5hsWTcUYNBxZNDM9A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-30T08:49:22Z"
  mac: ENC[AES256_GCM,data:pdayYTJNCO5q9tskosXxP1R9FZEgM8N5bTg+H6KBNen7DCS6jBiEIPJCzjzPMqH6ARzAiBPcOFiSVegEkOO6EZB2YUZQ2sFwMnyATGRF5CTQ/kR0PQQ10rjuNAqaAQQXXY/NLFfeLM1tSjsfoYdCanFnwvpp1rMTBw39++pGhoU=,iv:DkKlnpAJgj+acHZzCbAm/ns1u3GmLXWslJbQ+2/fgYU=,tag:eqoY5XSmba8gSHl/2/1Oig==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
  name: wallabag-container-env
  namespace: wallabag
type: Opaque
stringData:
  SYMFONY__ENV__DATABASE_USER: ENC[AES256_GCM,data:SQVKviiBG+E=,iv:hThTshpeRdO+K4ow0bz5+ZqIDJBJ+w3rVcwIbwhKaZ8=,tag:p+FhJMbmxxWrR2PDFRdjHA==,type:str]
  SYMFONY__ENV__DATABASE_PASSWORD: ENC[AES256_GCM,data:tTcMrMiFv2JQmQ==,iv:OGzNSpyA5bdfqRPe4r1ai5eBt6jv/N4IpgwyFoKbxcg=,tag:wDfxgKo0vXKse6NTf/wcgg==,type:str]
sops:
  age:
    - recipient: age1vtnndcu4fmcthtam7zqlpt2nuqms7vhfdmljs08zzxkrnjy7344qt0td4v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlRXNvMFkxZHJoUUpJeXY1
        ZlpLZDNHalg5bVU0d2F0REUzNnl0ZXJGK0ZNClRXdE5zUXNua0Y5NUhibmZmL2hz
        SWNLTUUxUE1YS093MU9mbmJHWmhYS1EKLS0tIGNvekFpbXpEOU5yZTZCOExYK2Yz
        QkJDM215ZWk5Q2wra3IraEJpRzMzSjgKC8LoInzJMzhVSR21MqjBo/Llt2kK+XxT
        WtYq8RBvMj1UqjGe+zm7MK+wHx+OkhmBttXbf5hsWTcUYNBxZNDM9A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-30T08:49:22Z"
  mac: ENC[AES256_GCM,data:pdayYTJNCO5q9tskosXxP1R9FZEgM8N5bTg+H6KBNen7DCS6jBiEIPJCzjzPMqH6ARzAiBPcOFiSVegEkOO6EZB2YUZQ2sFwMnyATGRF5CTQ/kR0PQQ10rjuNAqaAQQXXY/NLFfeLM1tSjsfoYdCanFnwvpp1rMTBw39++pGhoU=,iv:DkKlnpAJgj+acHZzCbAm/ns1u3GmLXWslJbQ+2/fgYU=,tag:eqoY5XSmba8gSHl/2/1Oig==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
