apiVersion: v1
kind: Secret
metadata:
  name: wallabag-container-env
  namespace: wallabag
type: Opaque
stringData:
  SYMFONY__ENV__DATABASE_USER: ENC[AES256_GCM,data:uOEnmgEoass=,iv:Ykbtx8GCsjKydkXWGlTDafqim+ui7W/5G1n3JaFEtvE=,tag:Pmun0YYsV4/dRNhJZay1SQ==,type:str]
  SYMFONY__ENV__DATABASE_PASSWORD: ENC[AES256_GCM,data:RJuGbXB0AHbdmA==,iv:2uZonZB4oO2lANDf3Wr1mhm9FdX05zQVYGv4EoiUnJY=,tag:siZjdG9mcy74mkbX+TMwGA==,type:str]
sops:
  age:
    - recipient: age1vtnndcu4fmcthtam7zqlpt2nuqms7vhfdmljs08zzxkrnjy7344qt0td4v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyTnIrUmhRTXl6Q201Y3Z4
        YVNMemJZNWhmZWgvc2xadEtERldFcThLWmc4Clo5QWMrL0JsUjZQZTRZQVAzYkpv
        TThES2dGZWk0S1l3ZVdXeXFSRUpXdVUKLS0tIFV6Z0poNHdCb2NId25SVjhMdnJq
        Q2o0KytzYnJHRTJ4MlVDUHNRNlZsK1kKVe+9iUg1UzKXlewtpbzIc8b2ahfJPCUc
        77FWZ5eo89FR69SuA7Pkq5fD5YpIeeeCa0CkYEU+QuPzJgn7fTzQ8Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-30T08:38:42Z"
  mac: ENC[AES256_GCM,data:CSiHR8GuqAC1D9t8CaIya7OeJXW+VCVMa0tH/WCjc81boo/nF1IkDWev5iS0UEZPw2S08uyD1+JcK3Q0Sr+r7iDZGhlOFQtKgqb5/ufQ4xhswGvZjkvOsfCgmk5P4pI52+qQ9kG8brS5BA36gFr5WF3uUkJeji6fJrX34Y2wxeQ=,iv:CQ5aEGUEWZCabC9Z2pc83Ap3f1eMy504i0E42LmmnNY=,tag:GA5mPaXmSRI1BNs1c2QpKw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
