apiVersion: v1
kind: Secret
metadata:
  name: wallabag-db-creds
  namespace: wallabag
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:ySvoS155iNU=,iv:t9TGtcsNN8vJXp/UEeW/uAhtvH3flt85CI8CIhphCho=,tag:+vBIuopxxwv2zQVWGSpGAg==,type:str]
  password: ENC[AES256_GCM,data:rk+9Z7DXnWbVtQ==,iv:spGOoLK9JzjAitJgo+8BgPvURy1e44gLkp3quOkKOi4=,tag:6x+3O+vXhXAv9UTGhieyRg==,type:str]
sops:
  age:
    - recipient: age1vtnndcu4fmcthtam7zqlpt2nuqms7vhfdmljs08zzxkrnjy7344qt0td4v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyTnIrUmhRTXl6Q201Y3Z4
        YVNMemJZNWhmZWgvc2xadEtERldFcThLWmc4Clo5QWMrL0JsUjZQZTRZQVAzYkpv
        TThES2dGZWk0S1l3ZVdXeXFSRUpXdVUKLS0tIFV6Z0poNHdCb2NId25SVjhMdnJq
        Q2o0KytzYnJHRTJ4MlVDUHNRNlZsK1kKVe+9iUg1UzKXlewtpbzIc8b2ahfJPCUc
        77FWZ5eo89FR69SuA7Pkq5fD5YpIeeeCa0CkYEU+QuPzJgn7fTzQ8Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-30T08:24:48Z"
  mac: ENC[AES256_GCM,data:yIyde42Dx5gVb5NwojCbSnVa1UljRn1bCSmfVaoIyqs8y8hxg5CxzPu7ehH9ck/GB+xwwSXko0ljyvXVYS6JSN4Pd00HRWkp7c834lIxlx1NmyaHajv1Ft9bGpbz6hfz+zc0JBr7pjnkcWUpt8tNXvypGKzgArN7cOXXsYgZqLI=,iv:QD6PvLRV929cDgMvtMiOCttQD/fCoADitu2qeoIbpDI=,tag:53VANn3wEGp0s+wpkZUJIg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
  name: wallabag-container-env
  namespace: wallabag
type: Opaque
stringData:
  SYMFONY__ENV__DATABASE_USER: ENC[AES256_GCM,data:uOEnmgEoass=,iv:Ykbtx8GCsjKydkXWGlTDafqim+ui7W/5G1n3JaFEtvE=,tag:Pmun0YYsV4/dRNhJZay1SQ==,type:str]
  SYMFONY__ENV__DATABASE_PASSWORD: ENC[AES256_GCM,data:OkuWvTcutKHmZQ==,iv:URYoqrKvV/jra+oyNZruF/3lMeqRNLIboItyzyJYf00=,tag:9nDqXL2hEVhj0l3zalxIOw==,type:str]
sops:
  age:
    - recipient: age1vtnndcu4fmcthtam7zqlpt2nuqms7vhfdmljs08zzxkrnjy7344qt0td4v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyTnIrUmhRTXl6Q201Y3Z4
        YVNMemJZNWhmZWgvc2xadEtERldFcThLWmc4Clo5QWMrL0JsUjZQZTRZQVAzYkpv
        TThES2dGZWk0S1l3ZVdXeXFSRUpXdVUKLS0tIFV6Z0poNHdCb2NId25SVjhMdnJq
        Q2o0KytzYnJHRTJ4MlVDUHNRNlZsK1kKVe+9iUg1UzKXlewtpbzIc8b2ahfJPCUc
        77FWZ5eo89FR69SuA7Pkq5fD5YpIeeeCa0CkYEU+QuPzJgn7fTzQ8Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-30T08:24:48Z"
  mac: ENC[AES256_GCM,data:yIyde42Dx5gVb5NwojCbSnVa1UljRn1bCSmfVaoIyqs8y8hxg5CxzPu7ehH9ck/GB+xwwSXko0ljyvXVYS6JSN4Pd00HRWkp7c834lIxlx1NmyaHajv1Ft9bGpbz6hfz+zc0JBr7pjnkcWUpt8tNXvypGKzgArN7cOXXsYgZqLI=,iv:QD6PvLRV929cDgMvtMiOCttQD/fCoADitu2qeoIbpDI=,tag:53VANn3wEGp0s+wpkZUJIg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
