---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: homepage

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - secret.yaml
  - configmap.yaml
  - rbac.yaml
  - service.yaml
  - deployment.yaml
  - httproute.yaml

labels:
  - pairs:
      app.kubernetes.io/name: homepage
