apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: homepage
  namespace: homepage
  annotations:
    kubernetes.io/service-account.name: homepage
sops:
  age:
    - recipient: age1vtnndcu4fmcthtam7zqlpt2nuqms7vhfdmljs08zzxkrnjy7344qt0td4v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyYm40VXUvbXJkNG8vUGpw
        T3prMEVRSjBhb3RjcXVjYVpLUWxyMFlNZ2k4CjdRQjN4d3hLNUd1dHNpZnh5RGhY
        VVErZ1BqME1pZDRCUFpXWTdzZTIwNVkKLS0tIHpQZS8zcjh3Rmp4TEp0TXBvZlQ4
        cnVYSzA2L0tMYS9aclN4Z1dPQzljbUEKuF3uF+Sf1DXYXjjFj7iiHdBz8vR3xifH
        eNXau0Wa7bZwRO+gITAQrr7wbM2XAzybIf1N9vYpwZN2KAzfVU9LEw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-26T09:21:08Z"
  mac: ENC[AES256_GCM,data:VbrjhwWhlkOeFuLJlXPwHilY7S54+m8oIWmswx+29ClCLvN7X2tmeqfhfj1hKXRxlfbFNN7k3J9DNsW9LvHshAhgjhFVnQDZPrihj/cgXmCpbfIf0WsScl0e8zsko0z+2rPM5FsTaDwTSMx5AergIev2IXD6vxIsfyWBUeGf9Ys=,iv:Uaj/3yxoX09s7qmtyx3oKRmvxO7B6BCINNZvrdx6+J4=,tag:VsT4Un9geGwY+nfTUzYEgw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
