---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: linkding
  namespace: linkding
  annotations:
    gethomepage.dev/group: Selfhosted
    gethomepage.dev/enabled: "true"
    gethomepage.dev/pod-selector: ""
    gethomepage.dev/icon: linkding.png
    gethomepage.dev/name: Linkding
spec:
  parentRefs:
    - name: eg
      namespace: envoy-gateway-system
      sectionName: https
  hostnames:
    - linkding.local
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: linkding
          port: 80
