---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: linkding

resources:
  - namespace.yaml
  - secrets.yaml
  - configmap.yaml
  - postgresql.yaml
  - deployment.yaml
  - service.yaml
  - httproute.yaml

labels:
  - pairs:
      app.kubernetes.io/name: linkding
