apiVersion: v1
kind: Secret
metadata:
  name: linkding-db-creds
  namespace: linkding
type: Opaque
stringData:
  username: ENC[AES256_GCM,data:9OWcNZWbnpg=,iv:DP2q1v9oGLcNygdl/111AcmCXc0O80fkUitmIKI8khg=,tag:kYk3cVT7OT0vuDOIoNynUw==,type:str]
  password: ENC[AES256_GCM,data:qBQFqTr07FSJvg==,iv:EKOLzi2TZq16ywRYyXxJVXGgz1vTv5Y+W6rTek6/MZQ=,tag:MW5Ck4UmGAxVbscdsnRwZA==,type:str]
sops:
  age:
    - recipient: age1vtnndcu4fmcthtam7zqlpt2nuqms7vhfdmljs08zzxkrnjy7344qt0td4v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUUFZiN1I1bXpIRVpIdUVh
        Z3dJNUdvQ1RtV2F3MmIzSTV4WGxQT0ZXNEZFCnhNZGtKZThpM3lNQTM4YlRVZGx4
        Smg1eGNsekRtR3lqTFU0Ukk2NHpoVGsKLS0tIEFNUk56c0V6T3MrODY3S2dQbk5w
        NzRuWkxINEw5Y04zK1o0WXpoSU1VczgKMNYatPN9GZ4B/lZtYDvBYOE9kGzbD6ku
        A6pmhwyzF2iE6jVBSkRumEwH/ApK3p2sX+OrtLyFsqXq43Ufhc9Oog==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-29T16:49:23Z"
  mac: ENC[AES256_GCM,data:LXKDPwmH47eG47n9wLvfxkzoANNJYnnQ9CySWnTmNMD+I9FI2kI+PPJDHjSrAzr1wXCQrXcek9uqVVR65sXevhXJtE7eeMYx1rb+/rsyMVnw9yQqLuLjNoADQJZ28HdZOqUB+j9RylK4V4FzbhxuGmOn2XAfSlD2flu7n0liwQc=,iv:YKo3GkQQF+6uYY0vJHTvEhUdco79rpK656tSn1cHPws=,tag:zWtEWu+P2kHh19Ag+nm3+w==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
  name: linkding-container-env
  namespace: linkding
type: Opaque
stringData:
  LD_SUPERUSER_NAME: ENC[AES256_GCM,data:Ko5KtW8=,iv:ytRoll9R8x96dCulSMLMrwmYf5KHBVo6YQR8vSKiIFA=,tag:ekWEQYOlhjJkIRwDipirJw==,type:str]
  LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:vhzQV93q7WapRA==,iv:CdTtOy0rBOoGiRNB8EpKPucoOZSITKJIY1ohrlxCb/M=,tag:5vsqCMZ+7zQc2jPKjnn0ZQ==,type:str]
  LD_DB_PASSWORD: ENC[AES256_GCM,data:lyLiQ5jrztAYsA==,iv:NPIyzvBMT/u1anWgAezIHIL3AJ0Pvu4p9ellVK3gPGs=,tag:dpMqSn2CNr5lqs8K6YJeLw==,type:str]
  LD_DB_USER: ENC[AES256_GCM,data:3BPGNHfnenc=,iv:9BGhBIO8EAWtnYAb3EXhFRfbwnW6uLJFUTTLofTNxZ8=,tag:zpT8azernvJVoc5/2Nwcgg==,type:str]
sops:
  age:
    - recipient: age1vtnndcu4fmcthtam7zqlpt2nuqms7vhfdmljs08zzxkrnjy7344qt0td4v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUUFZiN1I1bXpIRVpIdUVh
        Z3dJNUdvQ1RtV2F3MmIzSTV4WGxQT0ZXNEZFCnhNZGtKZThpM3lNQTM4YlRVZGx4
        Smg1eGNsekRtR3lqTFU0Ukk2NHpoVGsKLS0tIEFNUk56c0V6T3MrODY3S2dQbk5w
        NzRuWkxINEw5Y04zK1o0WXpoSU1VczgKMNYatPN9GZ4B/lZtYDvBYOE9kGzbD6ku
        A6pmhwyzF2iE6jVBSkRumEwH/ApK3p2sX+OrtLyFsqXq43Ufhc9Oog==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-29T16:49:23Z"
  mac: ENC[AES256_GCM,data:LXKDPwmH47eG47n9wLvfxkzoANNJYnnQ9CySWnTmNMD+I9FI2kI+PPJDHjSrAzr1wXCQrXcek9uqVVR65sXevhXJtE7eeMYx1rb+/rsyMVnw9yQqLuLjNoADQJZ28HdZOqUB+j9RylK4V4FzbhxuGmOn2XAfSlD2flu7n0liwQc=,iv:YKo3GkQQF+6uYY0vJHTvEhUdco79rpK656tSn1cHPws=,tag:zWtEWu+P2kHh19Ag+nm3+w==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
