apiVersion: v1
kind: Secret
metadata:
  name: linkding-db-creds
  namespace: linkding
type: kubernetes.io/basic-auth
stringData:
  LD_DB_USER: ENC[AES256_GCM,data:6fhxLircEF4=,iv:hekU5OdvZOXLJZ+465Gv7Vv4nDmPAbwsuJK5BWOm7Go=,tag:FsfSDOUjO5dEnGTSsKDq8w==,type:str]
  LD_DB_PASSWORD: ENC[AES256_GCM,data:lyLiQ5jrztAYsA==,iv:NPIyzvBMT/u1anWgAezIHIL3AJ0Pvu4p9ellVK3gPGs=,tag:dpMqSn2CNr5lqs8K6YJeLw==,type:str]
sops:
  age:
    - recipient: age1vtnndcu4fmcthtam7zqlpt2nuqms7vhfdmljs08zzxkrnjy7344qt0td4v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUUFZiN1I1bXpIRVpIdUVh
        Z3dJNUdvQ1RtV2F3MmIzSTV4WGxQT0ZXNEZFCnhNZGtKZThpM3lNQTM4YlRVZGx4
        Smg1eGNsekRtR3lqTFU0Ukk2NHpoVGsKLS0tIEFNUk56c0V6T3MrODY3S2dQbk5w
        NzRuWkxINEw5Y04zK1o0WXpoSU1VczgKMNYatPN9GZ4B/lZtYDvBYOE9kGzbD6ku
        A6pmhwyzF2iE6jVBSkRumEwH/ApK3p2sX+OrtLyFsqXq43Ufhc9Oog==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-29T15:54:38Z"
  mac: ENC[AES256_GCM,data:tSKUgvzQQXDMP5FWu/QkcVqWgW/YRdINOeNPjlSLVta9YGLhYkvlK5YXpGp/FOe2BPI/ccJMq5lNTHVAqYAbT0gv5ZSdGN8Mz1kRo/iqjDZehGuMl5ZAobXo5iOruExPOik6Udm5wl4KdEDE8TTu3X2cnFTb3/MUDqc5amHegsQ=,iv:ElJ39omxTK3AM4EWe6jr/Ci4giB9rNWAeXt2SxX910Q=,tag:rWx6XOvgSobwAlGLcHVAYA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
  name: linkding-container-env
  namespace: linkding
type: Opaque
stringData:
  LD_SUPERUSER_NAME: ENC[AES256_GCM,data:Ko5KtW8=,iv:ytRoll9R8x96dCulSMLMrwmYf5KHBVo6YQR8vSKiIFA=,tag:ekWEQYOlhjJkIRwDipirJw==,type:str]
  LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:vhzQV93q7WapRA==,iv:CdTtOy0rBOoGiRNB8EpKPucoOZSITKJIY1ohrlxCb/M=,tag:5vsqCMZ+7zQc2jPKjnn0ZQ==,type:str]
sops:
  age:
    - recipient: age1vtnndcu4fmcthtam7zqlpt2nuqms7vhfdmljs08zzxkrnjy7344qt0td4v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUUFZiN1I1bXpIRVpIdUVh
        Z3dJNUdvQ1RtV2F3MmIzSTV4WGxQT0ZXNEZFCnhNZGtKZThpM3lNQTM4YlRVZGx4
        Smg1eGNsekRtR3lqTFU0Ukk2NHpoVGsKLS0tIEFNUk56c0V6T3MrODY3S2dQbk5w
        NzRuWkxINEw5Y04zK1o0WXpoSU1VczgKMNYatPN9GZ4B/lZtYDvBYOE9kGzbD6ku
        A6pmhwyzF2iE6jVBSkRumEwH/ApK3p2sX+OrtLyFsqXq43Ufhc9Oog==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-29T15:54:38Z"
  mac: ENC[AES256_GCM,data:tSKUgvzQQXDMP5FWu/QkcVqWgW/YRdINOeNPjlSLVta9YGLhYkvlK5YXpGp/FOe2BPI/ccJMq5lNTHVAqYAbT0gv5ZSdGN8Mz1kRo/iqjDZehGuMl5ZAobXo5iOruExPOik6Udm5wl4KdEDE8TTu3X2cnFTb3/MUDqc5amHegsQ=,iv:ElJ39omxTK3AM4EWe6jr/Ci4giB9rNWAeXt2SxX910Q=,tag:rWx6XOvgSobwAlGLcHVAYA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
