apiVersion: v1
kind: Secret
metadata:
  name: linkding-db-creds
  namespace: linkding
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:Avg/O7u4ZOs=,iv:B8gKfcfjiC5U7bQpDiDXWfvV8rE8azEL5real9pN9Vs=,tag:70ffqpyHgEXPzA1jMjEGeA==,type:str]
  password: ENC[AES256_GCM,data:5VJSQYL/OlJeIA==,iv:Ehg//PlfXHDosc5HlUDsKsFA7+rtvlOvf+AwlOG+PmM=,tag:dmLWOttg8S3bDJt+9RJmLw==,type:str]
sops:
  age:
    - recipient: age1vtnndcu4fmcthtam7zqlpt2nuqms7vhfdmljs08zzxkrnjy7344qt0td4v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUUFZiN1I1bXpIRVpIdUVh
        Z3dJNUdvQ1RtV2F3MmIzSTV4WGxQT0ZXNEZFCnhNZGtKZThpM3lNQTM4YlRVZGx4
        Smg1eGNsekRtR3lqTFU0Ukk2NHpoVGsKLS0tIEFNUk56c0V6T3MrODY3S2dQbk5w
        NzRuWkxINEw5Y04zK1o0WXpoSU1VczgKMNYatPN9GZ4B/lZtYDvBYOE9kGzbD6ku
        A6pmhwyzF2iE6jVBSkRumEwH/ApK3p2sX+OrtLyFsqXq43Ufhc9Oog==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-29T15:03:35Z"
  mac: ENC[AES256_GCM,data:qySoDFDzSNgVwzgkYjHqIwGg8yk8TVgXkF1znqFvJSMoNX+aUmv9BjgrTg3Dwmp06ECRZUdEYTJJJTHV8nL7AQTl4XQlOa1pFHElwNw0ZDNdOkajjMxmf21i1WK8LuISrsmzzZ6ks7bHAvxPQ/botOD1vxKrBwKNzodJYP0DP3Y=,iv:Wjaf79H0pkuSE7tAwd3FGmr4bef0jh/k1A/KlBwRrrI=,tag:JcqisPyn2MtCHGlyMRMbnQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
  name: linkding-container-env
  namespace: linkding
type: Opaque
stringData:
  LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:vhzQV93q7WapRA==,iv:CdTtOy0rBOoGiRNB8EpKPucoOZSITKJIY1ohrlxCb/M=,tag:5vsqCMZ+7zQc2jPKjnn0ZQ==,type:str]
  LD_DB_PASSWORD: ENC[AES256_GCM,data:QSz+z4dX8lph7A==,iv:oG915vntSVIEkIEGPXqc3ZYrY0bpLhhFEQgmO2E1Dts=,tag:q2ERxdXjGIA+oGo8/mDNgw==,type:str]
sops:
  age:
    - recipient: age1vtnndcu4fmcthtam7zqlpt2nuqms7vhfdmljs08zzxkrnjy7344qt0td4v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUUFZiN1I1bXpIRVpIdUVh
        Z3dJNUdvQ1RtV2F3MmIzSTV4WGxQT0ZXNEZFCnhNZGtKZThpM3lNQTM4YlRVZGx4
        Smg1eGNsekRtR3lqTFU0Ukk2NHpoVGsKLS0tIEFNUk56c0V6T3MrODY3S2dQbk5w
        NzRuWkxINEw5Y04zK1o0WXpoSU1VczgKMNYatPN9GZ4B/lZtYDvBYOE9kGzbD6ku
        A6pmhwyzF2iE6jVBSkRumEwH/ApK3p2sX+OrtLyFsqXq43Ufhc9Oog==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-29T15:03:35Z"
  mac: ENC[AES256_GCM,data:qySoDFDzSNgVwzgkYjHqIwGg8yk8TVgXkF1znqFvJSMoNX+aUmv9BjgrTg3Dwmp06ECRZUdEYTJJJTHV8nL7AQTl4XQlOa1pFHElwNw0ZDNdOkajjMxmf21i1WK8LuISrsmzzZ6ks7bHAvxPQ/botOD1vxKrBwKNzodJYP0DP3Y=,iv:Wjaf79H0pkuSE7tAwd3FGmr4bef0jh/k1A/KlBwRrrI=,tag:JcqisPyn2MtCHGlyMRMbnQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
