apiVersion: v1
kind: Secret
metadata:
  name: linkding-container-creds
  namespace: linkding
type: Opaque
stringData:
  username: ENC[AES256_GCM,data:9OWcNZWbnpg=,iv:DP2q1v9oGLcNygdl/111AcmCXc0O80fkUitmIKI8khg=,tag:kYk3cVT7OT0vuDOIoNynUw==,type:str]
  LD_DB_USER: ENC[AES256_GCM,data:3BPGNHfnenc=,iv:9BGhBIO8EAWtnYAb3EXhFRfbwnW6uLJFUTTLofTNxZ8=,tag:zpT8azernvJVoc5/2Nwcgg==,type:str]
  LD_DB_PASSWORD: ENC[AES256_GCM,data:lyLiQ5jrztAYsA==,iv:NPIyzvBMT/u1anWgAezIHIL3AJ0Pvu4p9ellVK3gPGs=,tag:dpMqSn2CNr5lqs8K6YJeLw==,type:str]
  LD_SUPERUSER_NAME: ENC[AES256_GCM,data:Ko5KtW8=,iv:ytRoll9R8x96dCulSMLMrwmYf5KHBVo6YQR8vSKiIFA=,tag:ekWEQYOlhjJkIRwDipirJw==,type:str]
  LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:vhzQV93q7WapRA==,iv:CdTtOy0rBOoGiRNB8EpKPucoOZSITKJIY1ohrlxCb/M=,tag:5vsqCMZ+7zQc2jPKjnn0ZQ==,type:str]
sops:
  age:
    - recipient: age1vtnndcu4fmcthtam7zqlpt2nuqms7vhfdmljs08zzxkrnjy7344qt0td4v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUUFZiN1I1bXpIRVpIdUVh
        Z3dJNUdvQ1RtV2F3MmIzSTV4WGxQT0ZXNEZFCnhNZGtKZThpM3lNQTM4YlRVZGx4
        Smg1eGNsekRtR3lqTFU0Ukk2NHpoVGsKLS0tIEFNUk56c0V6T3MrODY3S2dQbk5w
        NzRuWkxINEw5Y04zK1o0WXpoSU1VczgKMNYatPN9GZ4B/lZtYDvBYOE9kGzbD6ku
        A6pmhwyzF2iE6jVBSkRumEwH/ApK3p2sX+OrtLyFsqXq43Ufhc9Oog==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-29T16:38:28Z"
  mac: ENC[AES256_GCM,data:UBvVvmauDYDdk/9SzAsnl7W0nxFo8zy6OjMtZ9SjlCXXCZI+iEMZ8IVcCzlSuAIa3D8JSiyi+xyr4E0cn2/qeIWW6wyNNQzMpmeReFudYTkq8FD5z+VXKvDgyE1EktVrz1gUu+6ONRSMTF9p83n1FD6zG1TAjQrKLNUyZELsTts=,iv:KEQL/B3hyXdOWsdTMbwmqoVunw3lEA2jQKQOdwHxu2Y=,tag:a9qqd8SY7SKV2nF3wu2BSg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
