---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: immich-server
  namespace: immich
  annotations:
    cert-manager.io/cluster-issuer: "local-ca"
    gethomepage.dev/group: Selfhosted
    gethomepage.dev/enabled: "true"
    gethomepage.dev/pod-selector: ""
    gethomepage.dev/icon: immich.png
    gethomepage.dev/name: Immich
spec:
  ingressClassName: nginx
  rules:
    - host: "immich.local"
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: immich-server
                port:
                  number: 80
  tls:
    - hosts:
        - immich.local
      secretName: immich-tls
