---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: immich-server
  namespace: immich
  annotations:
    cert-manager.io/cluster-issuer: "local-ca"
    gethomepage.dev/description: Immich
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Cluster Management
    gethomepage.dev/icon: immich.png
    gethomepage.dev/name: immich
spec:
  ingressClassName: nginx
  rules:
    - host: "immich.local"
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: immich-server
                port:
                  number: 80
  tls:
  - hosts:
      - immich.local
    secretName: immich-tls
