---
apiVersion: v1
kind: Secret
metadata:
  name: immich-postgres-user
  namespace: immich
type: Opaque
stringData:
  username: ENC[AES256_GCM,data:OJJ87aKZ,iv:eu/QfQxdSMaP0Vi1evVZB1uHLqMQsruAusERB43yUW0=,tag:+nSp3T2u9Jb9T4E2dP4eqA==,type:str]
  password: ENC[AES256_GCM,data:SJzEPjuPPcu7KuO/KNKr,iv:vGcwqfUswIWqrGoC1hzAx5ftH/OrgWbitVpH7GjBvWU=,tag:22N8groJ/1OopUOe44HB2g==,type:str]
sops:
  age:
    - recipient: age1vtnndcu4fmcthtam7zqlpt2nuqms7vhfdmljs08zzxkrnjy7344qt0td4v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBabkRjN3ZhdDlKeFRnUTF6
        RU9pVWsvTWh6TnJCTUJSNk1nOEUvL0xiYmhzCnRNRFFEVmpNd1pTcGR3M2JkVHhM
        cFdwcWNocGdvYndMVEhkSENlOUhsVkkKLS0tIFdBbW93bVY1WW5peEJyYldTMi9v
        Szd6cVVVK3BOV3ErLytlcnN2UU4yU2sKe4w6F1lNvpppMyVnT/74DywraHEQevib
        OSLXql0mcYZot3f69+Pzuxt5EqX450mkXgWlqU6A9WBbhd/Qg0TLrQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-29T08:44:36Z"
  mac: ENC[AES256_GCM,data:6w/K3oZLnnRhSIrSTClS1Od/twFnZJdP6ZVV2ImS36HZfwFIDsKGjIX7LnqRJqB2/PUh7RfQEjooBh67uQhLgnaB/xCFerpOmLrWzdv6w5PNSaF2QvtPTLSHmNxqwZF24HtKLPzq/FkveH+Sj/9ce0PsYQ3XBhquGlrmtDpjhfw=,iv:xt2Qjt/Pe8NIU/30U6hfsdiuYpnpwGuQvPd9ZAYK2DQ=,tag:WZFjGhguA524RxW0pSYoaw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
  name: immich-app-secrets
  namespace: immich
type: Opaque
stringData:
  DB_USERNAME: ENC[AES256_GCM,data:a2cq1oo2,iv:y3HTtWknHmxAeKn0B+b6lAW7mIfhCOv/FsbFquL9wI4=,tag:Rxp9F1xEqDHkQlC4XhgSeA==,type:str]
  DB_PASSWORD: ENC[AES256_GCM,data:wm2IQ3tnsGPP2GbQzvYc,iv:xGkK1ARBx8DVH2tU1baPw+Olp40v6UVpWZGC9S13tnU=,tag:6tUuGfyt9yKt/SB8iL2hVw==,type:str]
sops:
  age:
    - recipient: age1vtnndcu4fmcthtam7zqlpt2nuqms7vhfdmljs08zzxkrnjy7344qt0td4v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBabkRjN3ZhdDlKeFRnUTF6
        RU9pVWsvTWh6TnJCTUJSNk1nOEUvL0xiYmhzCnRNRFFEVmpNd1pTcGR3M2JkVHhM
        cFdwcWNocGdvYndMVEhkSENlOUhsVkkKLS0tIFdBbW93bVY1WW5peEJyYldTMi9v
        Szd6cVVVK3BOV3ErLytlcnN2UU4yU2sKe4w6F1lNvpppMyVnT/74DywraHEQevib
        OSLXql0mcYZot3f69+Pzuxt5EqX450mkXgWlqU6A9WBbhd/Qg0TLrQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-29T08:44:36Z"
  mac: ENC[AES256_GCM,data:6w/K3oZLnnRhSIrSTClS1Od/twFnZJdP6ZVV2ImS36HZfwFIDsKGjIX7LnqRJqB2/PUh7RfQEjooBh67uQhLgnaB/xCFerpOmLrWzdv6w5PNSaF2QvtPTLSHmNxqwZF24HtKLPzq/FkveH+Sj/9ce0PsYQ3XBhquGlrmtDpjhfw=,iv:xt2Qjt/Pe8NIU/30U6hfsdiuYpnpwGuQvPd9ZAYK2DQ=,tag:WZFjGhguA524RxW0pSYoaw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
