---
name: YAML lint

on:
  push:
    branches: [ main ]
    paths:
      - "**/*.yml"
      - "**/*.yaml"
      - "!.github/**"
  pull_request:
    branches: [ main ]
    paths:
      - "**/*.yml"
      - "**/*.yaml"
      - "!.github/**"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  yamllint:
    name: yamllint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Get changed YAML
        id: changed-files
        uses: bjw-s-labs/action-changed-files@1a5aeab1bfa64d0c4e786f501d5a3f1fad4a24da
        with:
          patterns: |
            **/*.yml
            **/*.yaml

      - name: Install yamllint
        if: steps.changed-files.outputs.any_changed == "true"
        run: |
          pip install yamllint

      - name: Run yamllint
        if: steps.changed-files.outputs.any_changed == "true"
        run: |
          echo "${{ steps.changed-files.outputs.changed_files }}"
          yamllint -c ./.yamllint.yaml \
            ${{ steps.changed-files.outputs.changed_files }}
           
  kubeconform:
    name: kubeconform
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Get changed manifests
        id: changed-files
        uses:  bjw-s-labs/action-changed-files@1a5aeab1bfa64d0c4e786f501d5a3f1fad4a24da
        with:
          patterns: |
            clusters/**/*.yaml
            k8s/**/*.yaml
            infra/**/*.yaml

      - name: Install kubeconform
        run: |
          curl -L https://github.com/yannh/kubeconform/releases/latest/download/kubeconform-linux-amd64.tar.gz \
            | tar -xz kubeconform
          sudo mv kubeconform /usr/local/bin/

      - name: Validate Kubernetes manifests
        run: |
          echo "${{ steps.changed-files.outputs.changed_files }}"
          kubeconform \
            -strict \
            -summary \
            --ignore-missing-schemas \
            ${{ steps.changed-files.outputs.changed_files }}
